# Generated by Django 4.2.7 on 2026-02-09 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(choices=[('corn', 'Corn'), ('tomato', 'Tomato'), ('wheat', 'Wheat'), ('potato', 'Potato'), ('soybean', 'Soybean'), ('lettuce', 'Lettuce'), ('carrot', 'Carrot'), ('pepper', 'Pepper')], max_length=50)),
                ('planting_date', models.DateField()),
                ('expected_harvest', models.DateField()),
                ('health_status', models.CharField(choices=[('healthy', 'Healthy'), ('at_risk', 'At Risk'), ('diseased', 'Diseased'), ('recovering', 'Recovering')], default='healthy', max_length=20)),
                ('area_acres', models.FloatField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('size_acres', models.FloatField()),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('soil_moisture', models.FloatField()),
                ('ph_level', models.FloatField()),
                ('light_intensity', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to='core.farm')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ResearchPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('authors', models.TextField()),
                ('abstract', models.TextField()),
                ('publication_date', models.DateField()),
                ('journal', models.CharField(max_length=200)),
                ('doi', models.CharField(max_length=100, unique=True)),
                ('pdf_url', models.URLField(blank=True)),
                ('keywords', models.TextField()),
                ('citation_count', models.IntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('crops_related', models.ManyToManyField(blank=True, to='core.crop')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('disease_prevention', 'Disease Prevention'), ('companion_planting', 'Companion Planting'), ('fertilizer', 'Fertilizer'), ('irrigation', 'Irrigation'), ('harvest_timing', 'Harvest Timing')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('confidence_score', models.FloatField()),
                ('implemented', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='core.farm')),
                ('research_papers', models.ManyToManyField(blank=True, to='core.researchpaper')),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='disease_photos/')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('affected_area', models.FloatField()),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_reports', to='core.crop')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_reports', to='core.farm')),
            ],
        ),
        migrations.AddField(
            model_name='crop',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='core.farm'),
        ),
        migrations.CreateModel(
            name='CompanionPlantingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_crop', models.CharField(max_length=50)),
                ('companion_crop', models.CharField(max_length=50)),
                ('relationship_type', models.CharField(choices=[('beneficial', 'Beneficial'), ('neutral', 'Neutral'), ('harmful', 'Harmful')], max_length=20)),
                ('benefit_description', models.TextField()),
                ('confidence_score', models.FloatField()),
                ('research_paper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.researchpaper')),
            ],
            options={
                'unique_together': {('primary_crop', 'companion_crop')},
            },
        ),
    ]
