# Generated by Django 4.2.7 on 2026-03-10 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('crop_variety', models.CharField(blank=True, max_length=100)),
                ('planting_date', models.DateField(blank=True, null=True)),
                ('expected_harvest_date', models.DateField(blank=True, null=True)),
                ('area_hectares', models.FloatField(default=1.0)),
                ('soil_type', models.CharField(max_length=50)),
                ('soil_nitrogen', models.FloatField()),
                ('soil_phosphorus', models.FloatField()),
                ('soil_potassium', models.FloatField()),
                ('soil_ph', models.FloatField()),
                ('season', models.CharField(max_length=50)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('rainfall', models.FloatField()),
                ('crop_recommendations', models.JSONField(blank=True, default=dict)),
                ('fertilizer_schedule', models.JSONField(blank=True, default=dict)),
                ('care_instructions', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crop_plans', to='core.farm')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crop_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
