# Generated by Django 4.2.7 on 2026-03-10 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cropplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='FertilizerQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(max_length=100)),
                ('farm_area', models.FloatField()),
                ('area_unit', models.CharField(default='hectare', max_length=20)),
                ('fertilizer_type', models.CharField(max_length=100)),
                ('quantity_per_unit', models.FloatField()),
                ('total_quantity', models.FloatField()),
                ('application_method', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FertilizerSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('sowing_date', models.DateField()),
                ('schedule_data', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NutrientDeficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('deficiency_type', models.CharField(choices=[('nitrogen', 'Nitrogen'), ('phosphorus', 'Phosphorus'), ('potassium', 'Potassium'), ('calcium', 'Calcium'), ('magnesium', 'Magnesium'), ('iron', 'Iron'), ('zinc', 'Zinc')], max_length=20)),
                ('symptoms', models.TextField()),
                ('leaf_image', models.ImageField(blank=True, null=True, upload_to='leaf_analysis/')),
                ('soil_nitrogen', models.FloatField(blank=True, null=True)),
                ('soil_phosphorus', models.FloatField(blank=True, null=True)),
                ('soil_potassium', models.FloatField(blank=True, null=True)),
                ('recommended_fertilizer', models.CharField(max_length=100)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganicFertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nutrient_content', models.JSONField(default=dict)),
                ('suitable_crops', models.TextField()),
                ('suitable_soil_types', models.TextField()),
                ('application_rate', models.CharField(max_length=100)),
                ('benefits', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WeatherBasedFertilizerAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('fertilizer_type', models.CharField(max_length=100)),
                ('weather_condition', models.CharField(max_length=100)),
                ('temperature', models.FloatField()),
                ('rainfall_forecast', models.CharField(max_length=200)),
                ('wind_speed', models.FloatField(blank=True, null=True)),
                ('recommendation', models.TextField()),
                ('best_application_date', models.DateField(blank=True, null=True)),
                ('warning_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SoilNutrientAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nitrogen_value', models.FloatField()),
                ('phosphorus_value', models.FloatField()),
                ('potassium_value', models.FloatField()),
                ('nitrogen_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('adequate', 'Adequate'), ('high', 'High')], max_length=20)),
                ('phosphorus_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('adequate', 'Adequate'), ('high', 'High')], max_length=20)),
                ('potassium_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('adequate', 'Adequate'), ('high', 'High')], max_length=20)),
                ('suggested_fertilizers', models.JSONField(default=list)),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soil_analyses', to='core.farm')),
            ],
        ),
        migrations.CreateModel(
            name='FertilizerRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('soil_type', models.CharField(max_length=50)),
                ('growth_stage', models.CharField(choices=[('seedling', 'Seedling'), ('vegetative', 'Vegetative'), ('flowering', 'Flowering'), ('fruiting', 'Fruiting'), ('maturity', 'Maturity')], max_length=20)),
                ('current_nitrogen', models.FloatField()),
                ('current_phosphorus', models.FloatField()),
                ('current_potassium', models.FloatField()),
                ('fertilizer_type', models.CharField(max_length=100)),
                ('npk_ratio', models.CharField(max_length=20)),
                ('deficiency_detected', models.CharField(max_length=200)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fertilizer_recommendations', to='core.cropplan')),
            ],
        ),
    ]
